# Generated by Django 5.2.7 on 2025-11-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_purchase_guest_email_purchase_guest_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='guest_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='guest_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='guest_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
