# Generated by Django 5.2.7 on 2025-12-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_alter_purchase_guest_email_alter_purchase_guest_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentwithreceipt',
            name='receipt_url',
        ),
        migrations.AddField(
            model_name='paymentwithreceipt',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
