# Generated by Django 5.2.7 on 2025-12-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_remove_paymentwithreceipt_receipt_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentwithreceipt',
            name='selected_numbers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
