# Generated by Django 5.2.7 on 2025-12-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_paymentwithreceipt_selected_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedetail',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('expired', 'Expired'), ('canceled', 'Canceled')], default='pending', max_length=16),
        ),
    ]
