# Generated by Django 5.2.7 on 2025-11-06 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Raffle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(default='draft', max_length=32)),
                # Use CharField in migrations to match models.py and allow tests
                # to insert non-numeric values (tests expect raw values like "abc").
                ('price_per_number', models.CharField(blank=True, max_length=64, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raffles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
