# Generated by Django 5.2.7 on 2025-11-10 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('finished', 'Finished')], default='draft', max_length=10),
        ),
    ]
