# Generated by Django 5.2.7 on 2025-11-11 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0002_raffle_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raffle',
            name='status',
        ),
    ]
