# Generated by Django 5.2.7 on 2025-11-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0003_remove_status_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raffle',
            name='image_url',
        ),
        migrations.AddField(
            model_name='raffle',
            name='image',
            field=models.ImageField(blank=True, upload_to='raffles/'),
        ),
    ]
